import { Theme } from "../../types/theme";

export const themes: Theme[] = [
  {
    id: "light",
    name: "Light",
    description: "Clean and bright theme for daytime use",
    colors: {
      primary: "#3B82F6",
      secondary: "#10B981",
      accent: "#F59E0B",
      background: "#FFFFFF",
      surface: "#F8FAFC",
      text: "#1F2937",
      textSecondary: "#6B7280",
      border: "#E5E7EB",
      success: "#10B981",
      warning: "#F59E0B",
      error: "#EF4444",
    },
  },
  {
    id: "dark",
    name: "Dark",
    description: "Elegant dark theme for comfortable viewing",
    colors: {
      primary: "#60A5FA",
      secondary: "#34D399",
      accent: "#FBBF24",
      background: "#111827",
      surface: "#1F2937",
      text: "#F9FAFB",
      textSecondary: "#D1D5DB",
      border: "#374151",
      success: "#34D399",
      warning: "#FBBF24",
      error: "#F87171",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep blue theme inspired by ocean depths",
    colors: {
      primary: "#0EA5E9",
      secondary: "#06B6D4",
      accent: "#8B5CF6",
      background: "#0F172A",
      surface: "#1E293B",
      text: "#F1F5F9",
      textSecondary: "#CBD5E1",
      border: "#334155",
      success: "#06B6D4",
      warning: "#F97316",
      error: "#EF4444",
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Nature-inspired green theme for tranquility",
    colors: {
      primary: "#059669",
      secondary: "#65A30D",
      accent: "#DC2626",
      background: "#14181B",
      surface: "#1C2617",
      text: "#F0FDF4",
      textSecondary: "#BBF7D0",
      border: "#365314",
      success: "#22C55E",
      warning: "#EAB308",
      error: "#DC2626",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm gradient theme with sunset colors",
    colors: {
      primary: "#F97316",
      secondary: "#EC4899",
      accent: "#8B5CF6",
      background: "#1C1917",
      surface: "#292524",
      text: "#FEF7F0",
      textSecondary: "#FED7AA",
      border: "#44403C",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
    },
  },
];
